import { Google } from '@mui/icons-material'
import { LoadingButton } from '@mui/lab'
import { Avatar, CircularProgress, Typography } from '@mui/material'
import { Stack } from '@mui/system'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { SocialIcon } from 'react-social-icons'
import styles from '../styles/Home.module.css'
import OpenLogin, { OpenLoginOptions } from '@toruslabs/openlogin'

const LOGIN_CONNECTIONS = {
  line: {
    typeOfLogin: "line",
    jwtParams: {
      domain: 'https://lzg2dndj.auth.dev.upbond.io',
      connection: "line",
      clientId: 'FoQ_Ri8rKSXkHf82GRzZK',
      scope: "openid email profile offline_access",
    },
    verifier: 'upbond-wallet-tesnet-line', // currently using 'upbond-rick-line'
    clientId: 'FoQ_Ri8rKSXkHf82GRzZK',
  },
};

const Home: NextPage = () => {
  const [isLoading, setIsLoading] = useState(false)
  const [openlogin, setOpenLogin] = useState<OpenLogin | null>(null)
  const [privKey, setPrivKey] = useState<string>('')

  const mount = async () => {
    try {
      setIsLoading(true)
      const ol = new OpenLogin({
        clientId: LOGIN_CONNECTIONS.line.clientId,
        network: 'testnet'
      })
      await ol.init()

      setPrivKey(ol.privKey)
      setOpenLogin(ol)
    } catch (error: any) {
      setIsLoading(false)
      console.error(error.message, '@error')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          You&apos;re logged in
        </h1>
        {
          isLoading ? (
            <Stack direction={'row'} alignItems='center' justifyContent={'center'}>
              <CircularProgress />
              <Typography>Loading ...</Typography>
            </Stack>
          ) : (
            <Stack direction={'column'} spacing={4} mt={5}>
              <Typography>Private Key {privKey}</Typography>
            </Stack>
          )
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
